spring:
  application:
    name: grievances-mgmt-service
  data:
    mongodb:
      uri: mongodb+srv://grv_user:${mongoDbPassword}@cluster0.efk7nvy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: grievance
      repositories:
        enabled: true